### ISSUE TITLE
Prepare for the initial release

### ISSUE THREAD

**Issue by mstechly** [QSI-BAQS/Jabalizer.jl#33]
Once we're ready, we should make an initial release.
I don't know how the release process looks like exactly for Julia, so I'll leave it for @ScottPJones to fill in the details on this one :)

Two questions I have are:
- Do we want to put it on "Julia's PyPI", if it exists?
- Can we have the version of the package automatically inferred? I know we have that for some Python packages
- Do we want to have some automation around the release? E.g. a GitHub action or a simple script?

**Comment by mstechly** [comment]
Then I think we could make the first release after solving #30 :)
When it's time, let's pair on this, we'll write down the process and close this issue.

**Comment by ScottPJones** [comment]
This will be done shortly - I've already made a request to register it
